" Some Linux distributions set filetype in /etc/vimrc.
" Clear filetype flags before changing runtimepath to force Vim to reload them.
"filetype off
"filetype plugin indent off
"set runtimepath+=$GOROOT/misc/vim
execute pathogen#infect()
syntax on
filetype plugin indent on

set tabstop=4
set shiftwidth=4

colorscheme koehler
set t_Co=256
